#!/bin/sh

# ensure that formatting is correct before pushing to the remote repository
dotnet tool restore
git diff --cached --name-only --diff-filter=ACM -z | xargs -0 dotnet fantomas 
git diff --cached --name-only --diff-filter=ACM -z | xargs -0 git add