#!/bin/sh

remote_name="$1"
remote_url="$2"
# Information about the commits which are being pushed is supplied as lines to
# the standard input in the form:
#
#   <local ref> <local oid> <remote ref> <remote oid>
# TODO: read these lines and use the list of 'refs to push' to inspect the 
# content of those refs and only format the changed files.

# sample read loop:
# while read local_ref local_oid remote_ref remote_oid
# do
#   // use local_ref, local_oid, remote_ref, remote_oid to compute file changes
# done

# ensure that formatting is correct before pushing to the remote repository
dotnet tool restore
git diff --cached --name-only --diff-filter=ACM -z | xargs -0 dotnet tool run fantomas 