// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection
open System.Runtime.CompilerServices

[<assembly: InternalsVisibleToAttribute("Fantomas.Tests")>]
[<assembly: AssemblyTitleAttribute("FantomasLib")>]
[<assembly: AssemblyProductAttribute("Fantomas")>]
[<assembly: AssemblyDescriptionAttribute("Source code formatter for F#")>]
[<assembly: AssemblyVersionAttribute("2.6.1")>]
[<assembly: AssemblyFileVersionAttribute("2.6.1")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] InternalsVisibleTo = "Fantomas.Tests"
    let [<Literal>] AssemblyTitle = "FantomasLib"
    let [<Literal>] AssemblyProduct = "Fantomas"
    let [<Literal>] AssemblyDescription = "Source code formatter for F#"
    let [<Literal>] AssemblyVersion = "2.6.1"
    let [<Literal>] AssemblyFileVersion = "2.6.1"
