// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("Fantomas")>]
[<assembly: AssemblyProductAttribute("Fantomas")>]
[<assembly: AssemblyDescriptionAttribute("Source code formatter for F#")>]
[<assembly: AssemblyVersionAttribute("2.7.1")>]
[<assembly: AssemblyFileVersionAttribute("2.7.1")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "Fantomas"
    let [<Literal>] AssemblyProduct = "Fantomas"
    let [<Literal>] AssemblyDescription = "Source code formatter for F#"
    let [<Literal>] AssemblyVersion = "2.7.1"
    let [<Literal>] AssemblyFileVersion = "2.7.1"
