<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <NoWarn>FS0988</NoWarn>
    <TargetFramework>net10.0</TargetFramework>
    <WarningsAsErrors>FS0025</WarningsAsErrors>
    <IsPackable>false</IsPackable>
    <RollForward>Major</RollForward>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="TestHelpers.fsi" />
    <Compile Include="TestHelpers.fs" />
    <Compile Include="UtilsTests.fs" />
    <Compile Include="QueueTests.fs" />
    <Compile Include="DefinesTests.fs" />
    <Compile Include="TriviaAssignmentTests.fs" />
    <Compile Include="FormattingSelectionOnlyTests.fs" />
    <Compile Include="ValidationTests.fs" />
    <Compile Include="FormatAstTests.fs" />
    <Compile Include="StackOverflowTests.fs" />
    <Compile Include="ContextTests.fs" />
    <Compile Include="CodeFormatterTests.fs" />
    <Compile Include="CodePrinterHelperFunctionsTests.fs" />
    <Compile Include="ASTTransformerTests.fs" />
    <Compile Include="CursorTests.fs" />
    <Compile Include="MultipleDefineCombinationsTests.fs" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Fantomas.Core\Fantomas.Core.fsproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="FSharp.Core" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="NUnit" />
    <PackageReference Include="NUnit3TestAdapter" />
    <PackageReference Include="FsCheck" />
    <PackageReference Include="FsUnit" />
    <PackageReference Include="System.IO.Abstractions.TestingHelpers" />
    <PackageReference Include="AltCover" PrivateAssets="all" />
  </ItemGroup>
</Project>