let XpkgDefaults () =
    { ToolPath = "./tools/xpkg/xpkg.exe"
      WorkingDir = "./"
      TimeOut = TimeSpan.FromMinutes 5.
      Package = null
      Version = if not isLocalBuild then buildVersion else "0.1.0.0"
      OutputPath = "./xpkg"
      Project = null
      Summary = null
      Publisher = null
      Website = null
      Details = "Details.md"
      License = "License.md"
      GettingStarted = "GettingStarted.md"
      Icons = []
      Libraries = []
      Samples = [] }
